spring:
  datasource:
    url: jdbc:mysql://{dbip}:{dbport}/pbs?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: {username}
    password: {password}
    driver-class-name: com.mysql.jdbc.Driver

db:
  schema: {dbschema}
table:
  pattern: {parttern}